AWSTemplateFormatVersion: '2010-09-09'     
Parameters:
  InstanceTypeParameter:
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large

  DBPwd:
    NoEcho: true
    Description: The database admin account password
    Type: String
    MinLength: 1
    MaxLength: 41
    AllowedPattern: ^[a-zA-Z0-9]*$
  
  Hobbies:
    Description: reason of the instance
    Type: String
    Default: "I am learning CloudFormation"

  Nameoftheinstance:
    Description: name of the instance
    Type: String
    Default: "dev env"

  Environment:
   Description: Environment of the instance
   Type: String
   Default: "dev"
   AllowedValues:
    - dev
    - test


Mappings:
  AMIIDMap:
    us-east-1:
      MyAMI1: ami-0ff8a91507f77f867
      MyAMI2: ami-0a584ac55a7631c0c
    us-west-1:
      MyAMI1: ami-0bdb828fd58c52235
      MyAMI2: ami-066ee5fd4a9ef77f1
    eu-west-1:
      MyAMI1: ami-047bb4163c506cd98
      MyAMI2: ami-0a7c483d527806435
    ap-northeast-1:
      MyAMI1: ami-06cd52961ce9f0d85
      MyAMI2: ami-053cdd503598e4a9d
    ap-southeast-1:
      MyAMI1: ami-08569b978cc4dfa10
      MyAMI2: ami-0be9df32ae9f92309
    us-east-2:
      MyAMI1: ami-058a8a5ab36292159

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ AMIIDMap, !Ref "AWS::Region", MyAMI1]
      InstanceType: !Ref InstanceTypeParameter
      SubnetId: !ImportValue 'ambroisenomo-SubnetID'
      SecurityGroupIds:
        - !ImportValue 'ambroisenomo-SecurityGroupID'
      UserData:
          Fn::Base64: !Sub |
             #!/bin/bash
             yum update -y
             yum install httpd -y
             systemctl start httpd
             systemctl enable httpd
             echo "Welcome to our first user data launch throught CloudFormation" > /var/www/html/index.html
  myEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2Instance
  
